### ISSUE TITLE
what is 0 or 1  mean in the training data?

### ISSUE THREAD

**Issue by fengpku** [QData/iGakco-SVM#23]
Hi,

I am trying to use FastSK, but a little confused about how to prepare the training dataset. 

For example, I want to train a model of ATAC-seq in K562 cells, should the positive data be real ATAC-seq data and negative data be randomized seqs? 

Does 0 represent positive seqs and 1 represent randomized negative seqs ?

Thanks a lot.

**Comment by jacklanchantin** [comment]
Positive data should be real positive sequences. You can generate negative in several ways (random sequences, shuffled positive sequences, etc).

1 represents positive, 0 represents negative
